### ISSUE TITLE
How could you add vue to the initial setup?

### ISSUE THREAD

**Issue by juanpasolano** [wondercraft-co/wonderplate-shopify-cli#3]

**Comment by julio-salas03** [comment]
Vite allows you to do this out-of-the-box: https://vitejs.dev/guide/#trying-vite-online

> You can also directly specify the project name and the template you want to use via additional command line options. For example, to scaffold a Vite + Vue project

**Comment by juanpasolano** [comment]
@julio-salas03 The problem is we are not initializing with the Vite CLI here; that scaffold is for you to start a new project. In our case, we are attaching a build to an ongoing project.
I think the easiest way is to provide a guide with steps to add it. We probably want guides for React and other frameworks, too, and supporting them all could be just a big mess. On the other hand, the steps to add them are relatively easy.
What do you think?

**Comment by juanpasolano** [comment]
This has been added to the docs.
https://wondercraft-co.github.io/wonderplate-shopify-cli/docs/vue.html
